name: kanban_board_app
description: "App Movil "
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  connectivity_plus: ^6.1.4
  flutter:
    sdk: flutter
  flutter_boardview: ^0.2.1
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.9.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
